[tool.briefcase]
project_name = "Book My Slot"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/bookmyslot"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.bookmyslot]
formal_name = "Book My Slot"
description = "My first application"
icon = "src/bookmyslot/resources/bookmyslot"
sources = ['src/bookmyslot']
requires = []


[tool.briefcase.app.bookmyslot.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.bookmyslot.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.bookmyslot.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.bookmyslot.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.bookmyslot.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
